/**
 * Define names of ipc events.
 */
module.exports = {
    ASYNC_GAZE_FOCUS_EVENT: 'ASYNC_GAZE_FOCUS_EVENT',
    ASYNC_LISTEN: 'ASYNC_LISTEN',

    CALIBRATE_TOBII_EYETRACKER: 'CALIBRATE_TOBII_EYETRACKER',
    CALIBRATE_TOBII_WHEN_IDLE: 'CALIBRATE_TOBII_WHEN_IDLE'
}